export const COUNTER_ACTION_INCREMENT = 'COUNTER_ACTION_INCREMENT'
export const COUNTER_ACTION_DECREMENT = 'COUNTER_ACTION_DECREMENT'
export const COUNTER_ACTION_VALUE_INCREMENT = 'COUNTER_ACTION_VALUE_INCREMENT'