export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'
export const COUNTER_VALUE_INCREMENT = 'COUNTER_VALUE_INCREMENT'

export const SEARCH_VALUES_STARTED = 'SEARCH_VALUES_STARTED'
export const SEARCH_VALUES_SUCCESS = 'SEARCH_VALUES_SUCCESS'
export const SEARCH_VALUES_FAILED = 'SEARCH_VALUES_FAILED'

export const SAVE_LOCAL_VALUE = 'SAVE_LOCAL_VALUE'
export const SAVE_LOCAL_VALUE_SUCCESS = 'SAVE_LOCAL_VALUE_SUCCESS'
export const GET_LOCAL_VALUE = 'GET_LOCAL_VALUE'
export const GET_LOCAL_VALUE_SUCCESS = 'GET_LOCAL_VALUE_SUCCESS'